name: Integration test
on: push

jobs:
  build:
    name: Run example
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Test example
      uses: docker://tkpd/gripmock:test
      with:
        entrypoint: test/example/entrypoint.sh

